version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - release-review-required

  - package-ecosystem: pip
    directory: /requirements/py311
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - release-review-required

  - package-ecosystem: docker
    directory: /images/base
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - release-review-required

  - package-ecosystem: docker
    directory: /images/python-runtime
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - release-review-required

  - package-ecosystem: docker
    directory: /images/python-wheelhouse-py311
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - release-review-required
